### ISSUE TITLE
cython is required but not list in setup.py

### ISSUE THREAD

**Issue by bung87** [taishi-i/nagisa#1]
will be failure while installing

**Comment by taishi-i** [comment]
Thanks for your comment.

Since cython is used in setup.py,
we need to install cython before installing this library. 
(e.g, pip install cython)
For the above reason, we don't list cython in setup.py.

If you install cython and the installation of this library fails,
we recommend you to use Anaconda.

**Comment by bung87** [comment]
is there a way make sure install cython completed before installing nagisa?I listed cython and nagisa in my project requirements.txt but it seems pip wont make sure cython installed even cython is priority in requirements.txt

**Comment by taishi-i** [comment]
> is there a way make sure install cython completed before installing nagisa?

Sorry, I'm not sure. However, there is a way to solve this problem.
Now, we face the same problem on the following site.
[How to specify install order for python pip?
](https://stackoverflow.com/questions/5394356/how-to-specify-install-order-for-python-pip)

To solve this problem, please execute `bash install-nagisa.sh` instead of executing `pip install -r requirements.txt`. Write a bash script that reads from your requirements file line by line and runs the pip command on it.

install-nagisa.sh
~~~
#!/bin/bash
for line in $(cat requirements.txt)
do
  pip install $line
done
~~~

requirements.txt
~~~
cython
numpy
six
nagisa
~~~
