### ISSUE TITLE
Suppress output messages

### ISSUE THREAD

**Issue by manga-ai** [taishi-i/nagisa#25]
Currently, every time I import nagisa, messages regarding nagisa and dynet appear.

Is there an option/argument to suppress these output messages?

**Comment by taishi-i** [comment]
Hi @manga-ai. Thank you for using nagisa!
Sorry. We can't turn off the output at import because it's hard-coded in DyNet. So, there is not an option/argument.

It is not a suitable method, but we can turn off the output with the following command by merging the standard error output with the standard output and not displaying the standard output.
``` 
python sample.py > /dev/null 2>&1
````

**Comment by manga-ai** [comment]
Thank you for the response!

I have also tried setting nagisa's logging levels to "Warning", so nagisa itself won't be logging more output.

**Comment by manga-ai** [comment]
Thank you for the response!

I have also tried setting nagisa's logging levels to "Warning", so nagisa itself won't be logging more output.
